### ISSUE TITLE
PDF remove Chinese

### ISSUE THREAD

**Issue by hei-my** [mkl-public/testarea-itext5#3]
[https://github.com/mkl-public/testarea-itext5/blob/master/src/test/java/mkl/testarea/itext5/content/RemovePageTextContent.java](url)
Hello, this project has helped me solve a lot of problems. Thank you very much.
However, it is a pity that this method is not good enough to remove Chinese after testing. May I ask how to remove Chinese effectively? thank you!!!

**Comment by mkl-public** [comment]
Please explain with example code and an example PDF to illustrate the issue with Chinese.

**Comment by mkl-public** [comment]
Without code and documents illustrating the issue, I cannot even start to determine what goes wrong here, let alone fix it.
